// yeh jo ap auth dekh rahay hain is k under () (i.e(auth)) issay kehtay hain group routing agar samajna ho
// toh word file main group route serach karlena
import type { Metadata } from "next";
import "../globals.css";

import { ClerkProvider } from '@clerk/nextjs'


export const metadata: Metadata = {
  title: "Borcelle - Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
